
# 各種変数
boxName    = "Box名 (vender/boxname) metadata.jsonと合わせておく"
boxUrl     = "./setup/metadata.json"
hostname   = "hostname"
ipAddress  = "192.168.33.10"
httpPort   = 8010
sshPort    = 2210
proxyHttp  = "http://proxy.mycompany.co.jp:8080/"
proxyHttps = "http://proxy.mycompany.co.jp:8080/"
syncLocal  = "./www"
syncServer = "/var/www"

# Vagrantの設定
Vagrant.configure(2) do |config|

  config.vm.box              = boxName
  config.vm.box_url          = boxUrl
  config.vm.box_check_update = true

  config.vm.provider "virtualbox" do |vb|
    # Vagrant で VirtualBox 5.0 の準仮想化を有効にする
    # Vagrant 1.7.3+
    # VirtualBox 5.0+
    vb.customize ['modifyvm', :id, '--paravirtprovider', 'kvm']

    # IPv6とDNSでのネットワーク遅延対策
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end

  # host名の設定
  config.vm.hostname = hostname

  # ipaddressの設定
  config.vm.network :private_network, ip: ipAddress

  # ポートの設定
  config.vm.network :forwarded_port, guest: 80, host: httpPort, id: "http", auto_correct: true
  config.vm.network :forwarded_port, guest: 22, host: sshPort,  id: "ssh" , auto_correct: true

  # フォルダ同期の設定
  config.vm.synced_folder syncLocal, syncServer

  # デフォルトでインストールするプラグイン
  config.plugin.add_dependency "vagrant-vbguest"
  config.plugin.add_dependency "vagrant-proxyconf"

  # proxyの設定
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = proxyHttp
    config.proxy.https    = proxyHttps
    config.proxy.no_proxy = "localhost,127.0.0.1"
  end

  # Apacheやphpの設定ファイルを転送(Vagrantユーザのホームディレクトリに配置される)
  config.vm.provision "file", source: "./setup/files/host",      destination: "host"
  config.vm.provision "file", source: "./setup/files/http.conf", destination: "httpd.conf"
  config.vm.provision "file", source: "./setup/files/php.ini",   destination: "php.ini"

  # 転送したファイルを本来の位置に移動
  config.vm.provision "shell", path: "./setup/scripts/move_files.sh"

  # Sync Folderが遅れてマウントされるためにhttpdが自動起動しない事への対策
  config.vm.provision "shell", path: "./setup/scripts/http_restart.sh", run: "always"
end
